.TH "E:/dev/bccb33-workspace/myVensim/src/flow.hpp" 3 "Version v0.1.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/dev/bccb33-workspace/myVensim/src/flow.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlow\fP"
.br
.RI "Represents a flow of resources or energy between two systems in a simulation model\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
