.TH "E:/dev/bccb33-workspace/myVensim/src/model.hpp" 3 "Version v0.1.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/dev/bccb33-workspace/myVensim/src/model.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModel\fP"
.br
.RI "Represents a simulation model containing systems and flows\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
