.TH "E:/dev/bccb33-workspace/myVensim/src/system.hpp" 3 "Version v0.1.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/dev/bccb33-workspace/myVensim/src/system.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSystem\fP"
.br
.RI "Represents an individual system within a simulation model\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
